# -*- coding: utf-8 -*-
"""
自动生成 —— 请勿手工编辑，改数据请改 blocksArt.json 后重跑
gen_blocksart_data.py。

数据来源：blocksArt.json
（https://github.com/TgkRuobin/vue3-mcpixelart/blob/main/src/assets/data/blocksArt.json）

每行：(分类英文, 分类中文, 方块中文名, 方块英文 ID, normal 颜色 hex)
仅保留 normal 颜色值，用于按颜色分组构建调色板。
"""

BLOCKS_ART_ROWS = [
    ("wool", "羊毛", "白色羊毛", "white_wool", "#ABABAB"),
    ("wool", "羊毛", "橙色羊毛", "orange_wool", "#BA6D2C"),
    ("wool", "羊毛", "品红色羊毛", "magenta_wool", "#9941BA"),
    ("wool", "羊毛", "淡蓝色羊毛", "light_blue_wool", "#5884BA"),
    ("wool", "羊毛", "黄色羊毛", "yellow_wool", "#C5C52C"),
    ("wool", "羊毛", "黄绿色羊毛", "lime_wool", "#6DB015"),
    ("wool", "羊毛", "粉红色羊毛", "pink_wool", "#D06D8E"),
    ("wool", "羊毛", "灰色羊毛", "gray_wool", "#414141"),
    ("wool", "羊毛", "淡灰色羊毛", "light_gray_wool", "#848484"),
    ("wool", "羊毛", "青色羊毛", "cyan_wool", "#416D84"),
    ("wool", "羊毛", "紫色羊毛", "purple_wool", "#6D3699"),
    ("wool", "羊毛", "蓝色羊毛", "blue_wool", "#2C4199"),
    ("wool", "羊毛", "棕色羊毛", "brown_wool", "#58412C"),
    ("wool", "羊毛", "绿色羊毛", "green_wool", "#586D2C"),
    ("wool", "羊毛", "红色羊毛", "red_wool", "#842C2C"),
    ("wool", "羊毛", "黑色羊毛", "black_wool", "#151515"),
    ("carpet", "地毯", "白色地毯", "white_carpet", "#ABABAB"),
    ("carpet", "地毯", "橙色地毯", "orange_carpet", "#BA6D2C"),
    ("carpet", "地毯", "品红色地毯", "magenta_carpet", "#9941BA"),
    ("carpet", "地毯", "淡蓝色地毯", "light_blue_carpet", "#5884BA"),
    ("carpet", "地毯", "黄色地毯", "yellow_carpet", "#C5C52C"),
    ("carpet", "地毯", "黄绿色地毯", "lime_carpet", "#6DB015"),
    ("carpet", "地毯", "粉红色地毯", "pink_carpet", "#D06D8E"),
    ("carpet", "地毯", "灰色地毯", "gray_carpet", "#414141"),
    ("carpet", "地毯", "淡灰色地毯", "light_gray_carpet", "#848484"),
    ("carpet", "地毯", "青色地毯", "cyan_carpet", "#416D84"),
    ("carpet", "地毯", "紫色地毯", "purple_carpet", "#6D3699"),
    ("carpet", "地毯", "蓝色地毯", "blue_carpet", "#2C4199"),
    ("carpet", "地毯", "棕色地毯", "brown_carpet", "#58412C"),
    ("carpet", "地毯", "绿色地毯", "green_carpet", "#586D2C"),
    ("carpet", "地毯", "红色地毯", "red_carpet", "#842C2C"),
    ("carpet", "地毯", "黑色地毯", "black_carpet", "#151515"),
    ("glass", "玻璃", "白色玻璃", "white_stained_glass", "#ABABAB"),
    ("glass", "玻璃", "橙色玻璃", "orange_stained_glass", "#BA6D2C"),
    ("glass", "玻璃", "品红色玻璃", "magenta_stained_glass", "#9941BA"),
    ("glass", "玻璃", "淡蓝色玻璃", "light_blue_stained_glass", "#5884BA"),
    ("glass", "玻璃", "黄色玻璃", "yellow_stained_glass", "#C5C52C"),
    ("glass", "玻璃", "黄绿色玻璃", "lime_stained_glass", "#6DB015"),
    ("glass", "玻璃", "粉红色玻璃", "pink_stained_glass", "#D06D8E"),
    ("glass", "玻璃", "灰色玻璃", "gray_stained_glass", "#414141"),
    ("glass", "玻璃", "淡灰色玻璃", "light_gray_stained_glass", "#848484"),
    ("glass", "玻璃", "青色玻璃", "cyan_stained_glass", "#416D84"),
    ("glass", "玻璃", "紫色玻璃", "purple_stained_glass", "#6D3699"),
    ("glass", "玻璃", "蓝色玻璃", "blue_stained_glass", "#2C4199"),
    ("glass", "玻璃", "棕色玻璃", "brown_stained_glass", "#58412C"),
    ("glass", "玻璃", "绿色玻璃", "green_stained_glass", "#586D2C"),
    ("glass", "玻璃", "红色玻璃", "red_stained_glass", "#842C2C"),
    ("glass", "玻璃", "黑色玻璃", "black_stained_glass", "#151515"),
    ("concrete", "混凝土", "白色混凝土", "white_concrete", "#ABABAB"),
    ("concrete", "混凝土", "橙色混凝土", "orange_concrete", "#BA6D2C"),
    ("concrete", "混凝土", "品红色混凝土", "magenta_concrete", "#9941BA"),
    ("concrete", "混凝土", "淡蓝色混凝土", "light_blue_concrete", "#5884BA"),
    ("concrete", "混凝土", "黄色混凝土", "yellow_concrete", "#C5C52C"),
    ("concrete", "混凝土", "黄绿色混凝土", "lime_concrete", "#6DB015"),
    ("concrete", "混凝土", "粉红色混凝土", "pink_concrete", "#D06D8E"),
    ("concrete", "混凝土", "灰色混凝土", "gray_concrete", "#414141"),
    ("concrete", "混凝土", "淡灰色混凝土", "light_gray_concrete", "#848484"),
    ("concrete", "混凝土", "青色混凝土", "cyan_concrete", "#416D84"),
    ("concrete", "混凝土", "紫色混凝土", "purple_concrete", "#6D3699"),
    ("concrete", "混凝土", "蓝色混凝土", "blue_concrete", "#2C4199"),
    ("concrete", "混凝土", "棕色混凝土", "brown_concrete", "#58412C"),
    ("concrete", "混凝土", "绿色混凝土", "green_concrete", "#586D2C"),
    ("concrete", "混凝土", "红色混凝土", "red_concrete", "#842C2C"),
    ("concrete", "混凝土", "黑色混凝土", "black_concrete", "#151515"),
    ("terracotta", "陶瓦", "白色陶瓦", "white_terracotta", "#B4988A"),
    ("terracotta", "陶瓦", "橙色陶瓦", "orange_terracotta", "#89461F"),
    ("terracotta", "陶瓦", "品红色陶瓦", "magenta_terracotta", "#804B5D"),
    ("terracotta", "陶瓦", "淡蓝色陶瓦", "light_blue_terracotta", "#605D77"),
    ("terracotta", "陶瓦", "黄色陶瓦", "yellow_terracotta", "#A0721F"),
    ("terracotta", "陶瓦", "黄绿色陶瓦", "lime_terracotta", "#58642D"),
    ("terracotta", "陶瓦", "粉红色陶瓦", "pink_terracotta", "#8A4243"),
    ("terracotta", "陶瓦", "灰色陶瓦", "gray_terracotta", "#31231E"),
    ("terracotta", "陶瓦", "淡灰色陶瓦", "light_gray_terracotta", "#745C54"),
    ("terracotta", "陶瓦", "青色陶瓦", "cyan_terracotta", "#4B4F4F"),
    ("terracotta", "陶瓦", "紫色陶瓦", "purple_terracotta", "#693E4B"),
    ("terracotta", "陶瓦", "蓝色陶瓦", "blue_terracotta", "#41354F"),
    ("terracotta", "陶瓦", "棕色陶瓦", "brown_terracotta", "#412B1E"),
    ("terracotta", "陶瓦", "绿色陶瓦", "green_terracotta", "#414624"),
    ("terracotta", "陶瓦", "红色陶瓦", "red_terracotta", "#7A3327"),
    ("terracotta", "陶瓦", "黑色陶瓦", "black_terracotta", "#1F120D"),
    ("mine", "矿物", "红石块", "redstone_block", "#DC0000"),
    ("mine", "矿物", "铁块", "iron_block", "#909090"),
    ("mine", "矿物", "石英块", "quartz_block", "#DCD9D3"),
    ("mine", "矿物", "金块", "gold_block", "#D7CD42"),
    ("mine", "矿物", "钻石块", "diamond_block", "#4FBCB7"),
    ("mine", "矿物", "青金石块", "lapis_block", "#3F6EDC"),
    ("mine", "矿物", "绿宝石块", "emerald_block", "#00BB32"),
    ("mine", "矿物", "铁矿", "raw_iron_block", "#BA967E"),
    ("others", "其他", "草方块", "grass_block", "#6D9930"),
    ("others", "其他", "沙石", "sandstone", "#D5C98C"),
    ("others", "其他", "浮冰", "packed_ice", "#8A8ADC"),
    ("others", "其他", "树叶", "oak_leaves", "#006A00"),
    ("others", "其他", "雪块", "snow_block", "#DCDCDC"),
    ("others", "其他", "黏土块", "clay", "#8D909E"),
    ("others", "其他", "土径", "dirt_path", "#825E42"),
    ("others", "其他", "石头", "stone", "#606060"),
    ("others", "其他", "木头", "oak_wood", "#7B663E"),
    ("others", "其他", "灰化土", "podzol", "#6F4A2A"),
    ("others", "其他", "下界岩", "netherrack", "#600100"),
    ("others", "其他", "绯红菌岩", "crimson_nylium", "#A3292A"),
    ("others", "其他", "绯红菌柄", "crimson_stem", "#7F3653"),
    ("others", "其他", "绯红菌核", "crimson_hyphae", "#4F1519"),
    ("others", "其他", "诡异菌岩", "warped_nylium", "#126C73"),
    ("others", "其他", "诡异菌柄", "warped_stem", "#327A78"),
    ("others", "其他", "诡异菌核", "warped_hyphae", "#4A2535"),
    ("others", "其他", "诡异疣块", "warped_wart_block", "#119B72"),
    ("others", "其他", "深板岩", "deepslate", "#565656"),
]
